networks:
  reptrack-network:
    driver: bridge
services:
  rt_db:
    image: postgres
    networks:
      - reptrack-network
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - 5432:5432
    volumes:
      - "reptrack-db-data:/var/lib/postgresql/data"
  rt_server:
    build: .
    depends_on:
      - rt_db
    networks:
      - reptrack-network
    ports:
      - ${PORT}:${PORT}
    volumes:
      - "./:/usr/src/reptrack/server"
      - "reptrack-nodemodules:/usr/src/reptrack/server/node_modules"

volumes:
  reptrack-nodemodules:
  reptrack-db-data: