name: Client:Tests

on: pull_request

jobs:
  jest-run:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          working-directory: ./client
          node-version: 18.15.0
      - uses: pnpm/action-setup@v2
        with:
          working-directory: ./client
          version: 8.1.1
      - run: pnpm install
      - run: pnpm test:unit

  # cypress-run:
  #   name: Cypress e2e
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - uses: pnpm/action-setup@v2
  #       with:
  #         working-directory: ./next-client
  #         version: 8.1.1
  #     # Install NPM dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v5
  #       with:
  #         working-directory: ./next-client
  #         build: pnpm build
  #         start: pnpm start